apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 2
  template:
    metadata:
      name: deomp-nginx-job
      labels:
        app: batch-task
    spec:
      containers:
        - name: nginx-task
          image: busybox:latest
          command: ["sh", "-c", "echo hello Muhammad Sajid && sleep 10"]
      restartPolicy: Never
~