apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: nginx
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
